Add Stack Implementation in C
ThePrimeagen/yt pull request #1
Opened 2020-09-22 19:30 UTC by hemanth-kotagiri

2020-09-22 20:27 UTC, ThePrimeagen requested changes

2020-09-22 20:27 UTC, ThePrimeagen commented on ds/linked_list/src/ll.c
> +#include <stdio.h>
I like everything you done!

BUT!!!

2020-09-22 20:27 UTC, ThePrimeagen commented on ds/linked_list/src/ll.c
> +struct Node* top = NULL;
Move into its own struct

2020-09-22 20:27 UTC, ThePrimeagen commented on ds/linked_list/src/ll.c
> +void push(int value){
Spacing!  I don't have clang format set, but i'll get that shortly for this project.

Second, `return_type method_name(args) {` please :7

Also please name them with stack_push and stack_pop.  Just feels more ceezy :)

2020-09-22 20:27 UTC, ThePrimeagen commented on ds/linked_list/src/ll.c
> +    printf("\nYayayayayayayayaya pushed!!!\n\n");
no prints!

2020-09-22 20:27 UTC, ThePrimeagen commented on ds/linked_list/src/ll.c
> +    printf("\nYayayayayayayayaya pushed!!!\n\n");
There are a few of them, you keep them :)

2020-09-22 20:27 UTC, ThePrimeagen commented on ds/linked_list/src/ll.c
> +void showAllElements(){
this is excellent.  Could you make it work with both Q or S?

2020-09-22 20:27 UTC, ThePrimeagen commented on ds/linked_list/src/ll.c
> +void pop(){
Please return the popp'd value.

2020-09-22 20:27 UTC, ThePrimeagen commented on ds/linked_list/src/ll.c
> +    if(top == NULL){
also follow the style I was using.  I'll have to get clang format shortly.

2020-09-22 20:27 UTC, ThePrimeagen commented on ds/linked_list/src/ll.c
> +struct Node* top = NULL;
name top to tail.  that way it is consistent with the video :)

2020-09-22 20:27 UTC, ThePrimeagen commented on ds/linked_list/src/ll.c
> +void showAllElements(){
likely two methods, but you got it :)

2020-09-22 20:27 UTC, ThePrimeagen commented on ds/linked_list/src/ll.c
> +    int value, given;
Can we make it so you can create S or Q?

2020-09-22 20:27 UTC, ThePrimeagen commented on ds/linked_list/src/ll.c
> +    while(given!=5);
style guide :)

2020-09-22 21:50 UTC, hemanth-kotagiri commented
@ThePrimeagen just committed new changes. Check'em out! :smile:

2020-09-22 21:53 UTC, hemanth-kotagiri commented on ds/linked_list/src/ll.c
> +void push(int value){
Yes, done in the recent commit.

2020-09-22 21:54 UTC, hemanth-kotagiri commented on ds/linked_list/src/ll.c
> +    printf("\nYayayayayayayayaya pushed!!!\n\n");
Okay.

2020-09-22 21:54 UTC, hemanth-kotagiri commented on ds/linked_list/src/ll.c
> +void showAllElements(){
Yes, made another function for Queue as well. Check it out!

2020-09-22 21:54 UTC, hemanth-kotagiri commented on ds/linked_list/src/ll.c
> +void pop(){
Done!

2020-09-22 21:54 UTC, hemanth-kotagiri commented on ds/linked_list/src/ll.c
> +struct Node* top = NULL;
Also done.

2020-09-22 21:55 UTC, hemanth-kotagiri commented on ds/linked_list/src/ll.c
> +    int value, given;
Yes, created two different prompt functions to create S or Q.

2020-09-23 15:05 UTC, ThePrimeagen requested changes

2020-09-23 15:05 UTC, ThePrimeagen commented on ds/linked_list/src/ll.c
> +struct StackNode* tail = NULL;
Could you please put `tail` into a struct, like down below with `Queue`.  That way it feels ceezy.  Also shows that you can have many stacks easily.

2020-09-23 15:05 UTC, ThePrimeagen commented on ds/linked_list/src/ll.c
> +struct StackNode* tail = NULL;
You'll also notice that `Queue` keeps track of its size.  Please do that too.

```c
struct Queue {
    struct Node* head;	    struct Node* head;
    struct Node* tail;	    struct Node* tail;
    size_t size;	    size_t size;
};
```

2020-09-23 15:07 UTC, hemanth-kotagiri commented on ds/linked_list/src/ll.c
> +struct StackNode* tail = NULL;
Awesome. Will implement that. How is the style guide right now? is it okay?

2020-09-23 15:09 UTC, ThePrimeagen requested changes

2020-09-23 15:09 UTC, ThePrimeagen commented on ds/linked_list/src/ll.c
> +struct StackNode* tail = NULL;
Things are mostly there.

2 things:
1.  No omitted `{` from ifs (you have one with return)
2.  Don't treat if like a function.  i.e. `if(` but instead `if (`

2020-10-02 14:09 UTC, merged